function parseMagnetizationData(obj, magnetizationData)
    toAdd = array2table([magnetizationData.Raw{:, SQUIDDataFile.MomentFieldsRaw}], 'VariableNames', obj.MagnetizationFieldsParsed);
    toAdd.TemperatureRounded = round(toAdd.TemperatureRounded / 0.05) * 0.05;

    toAdd.Moment = ((toAdd.Moment ./ magnetizationData.Header.Moles) ...
        - (SQUIDDataFile.EicosaneXdm * magnetizationData.Header.EicosaneMoles .* toAdd.Field) ...
        - (magnetizationData.Header.Xdm .* toAdd.Field)) ...
        ./ 5585;
    toAdd.MomentErr = ((toAdd.MomentErr ./ magnetizationData.Header.Moles) ...
        - (SQUIDDataFile.EicosaneXdm * magnetizationData.Header.EicosaneMoles .* toAdd.Field) ...
        - (magnetizationData.Header.Xdm .* toAdd.Field)) ...
        ./ 5585;

    obj.Parsed = [obj.Parsed; toAdd];
end